### ISSUE TITLE
Setup CD on develop branch

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#10]
Every commit on develop branch should automatically get deployed to gh pages. Currently we do a `npm run deploy` locally to make a deployment and would like this process to be automated.

**Comment by neo773** [comment]
@rishi-raj-jain  Damn, 9 seconds difference, canceling my attempt

**Comment by rishi-raj-jain** [comment]
Hahah, thanks! We both seem to be crushing it.

**Comment by tusharmath** [comment]
Fantastic guys! Looking forward to your PRs :)
