### ISSUE TITLE
fix: `write-good` lint errors

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#107]
Current build fails on `develop` with a few error `write-good` lint errors. 

Fix all of them for docs/ files.

**Comment by neo773** [comment]
/attempt #107

@tusharmath 
Could I get assigned, haven’t worked on a new issue in a while.

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;26 tailcallhq bounties <br/> + 54 bounties from 18 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">tailcallhq/tailcall#1099, tailcallhq/tailcall#1121</div> | [Cancel attempt](https://console.algora.io/api/bounties/clscvqx7m0002l90fbix9u6wb/cancel-attempt) |

**Comment by ibishal** [comment]
/attempt #107


<div id="algora" />

| [Algora profile](https://console.algora.io/@/ibishal) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ibishal | 1 bounty from 1 project | <div align="center">TypeScript, Scala, <br />Rust</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clscvqx7m0002l90fbix9u6wb/cancel-attempt) |

**Comment by ayewo** [comment]
Would like to be assigned to this ✋.
