### ISSUE TITLE
document `omit`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#114]
The omit operator exists, but isn't documented. Add a document for omit.

- Explain how it works.
- Show an example of omit.
- Add links of omit to modify and vice versa
- Explain how omit is different than modify(omit: true)

**Comment by neo773** [comment]
/attempt #114

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;29 tailcallhq bounties <br/> + 60 bounties from 18 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clt6ded700002jx0ft7904i3x/cancel-attempt) |
