### ISSUE TITLE
Write a guide about showcase 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#116]
`showcase` is a server setting that remains undocumented. An attempt was made here: https://github.com/tailcallhq/tailcallhq.github.io/pull/101 but never reached completion.

- Update `@server` with the `showcase` setting.
- Why is it available ~ To try out random configurations hosted
- Performance considerations with using showcase (it's slow)

**Comment by neo773** [comment]
/attempt #116 

@tusharmath 
Could I get assigned?

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;30 tailcallhq bounties <br/> + 60 bounties from 18 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clt6f9rnp0002lf0fe39qz6df/cancel-attempt) |

**Comment by tusharmath** [comment]
Removing @neo773  from here since he is attempting on #125

**Comment by vinfinity7** [comment]
![image](https://github.com/tailcallhq/tailcallhq.github.io/assets/122719607/bc259547-0274-43c5-949e-a0cdf4e0f653)
Hi , So i gotta study about this solution and elaborate about this, is that all or am i missing something  @tusharmath ?
