### ISSUE TITLE
doc: mustache tempaltes

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#117]
Tailcall allows the use of mustache templates in various places of the configuration. Write a guide about the power it gives to the developers and it's limitations.

**Requirements**
- Explain what it does and why do we need it.
- List down all the places where mustache templates can be used.
- Link to `context.md` in the document for further reading.
- Back link to `mustache.md` in the `context.md`.
- Make no grammatical or spelling errors.
- Keep the guide tone neutral, non non-emotional.
- Keep the writing style free-flowing and engaging.
- Fact-check everything, connect on Discord if you are confused.
- Make the writing cohesive, to the point, and related to the title.

**PS: DON'T CREATE LOW-EFFORT CHATGPT GENERATED CONTENT!**

**Comment by rajdip-b** [comment]
Can I be assigned?

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by kaf-lamed-beyt** [comment]
@tusharmath, I'm attempting this and I'd love to be assigned. 

/attempt

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kaf-lamed-beyt) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kaf-lamed-beyt | 7 bounties from 3 projects | <div align="center">JavaScript, HTML, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clt6g9ubc0002la0fxvosyk3g/cancel-attempt) |
