### ISSUE TITLE
CSS Fix: code shifting on the home page

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#118]
On the home page when you switch between the "get started" code snippets, the width of the columns change, which is unexpected. This should be a simple CSS fix.

**Technical Requirements**
- No JS, use only CSS to make the fix.
- Ensure CI passes.
- Ensure the fix is responsive and works on all screens sizes.

<img width="1728" alt="Screenshot 2024-02-28 at 9 06 12 PM" src="https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/1e3181a3-9d70-4dbc-bd20-266722d82cbf">

<img width="1728" alt="Screenshot 2024-02-28 at 9 06 22 PM" src="https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/cba443e4-8e37-4fda-845a-1fae467fff5e">

<img width="1728" alt="Screenshot 2024-02-28 at 9 06 30 PM" src="https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/e07d712c-e283-470e-bf75-af5ed060f301">

**Comment by 35C4n0r** [comment]
@tusharmath I would like to attempt this one.

**Comment by tusharmath** [comment]
@35C4n0r Go for it.

**Comment by 35C4n0r** [comment]
/attempt #118

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clt6l9ilt0004l70gbxgy61l4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by MayorChristopher** [comment]
understood
