### ISSUE TITLE
document `link`

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#125]
The link operator exists, but isn't documented. Add a document for link.

- Explain how it works.
- Show an example of link.
- What are types supported by link

**Comment by neo773** [comment]
/attempt #125
Can I get assigned?
<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;30 tailcallhq bounties <br/> + 61 bounties from 18 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">tailcallhq/tailcallhq.github.io#116</div> | [Cancel attempt](https://console.algora.io/api/bounties/clt9xcw2m0002l60fbivvwh5z/cancel-attempt) |

**Comment by Bhavyajain21** [comment]
@tusharmath Please review the PR
