### ISSUE TITLE
Write a guide about using custom scalars

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#136]
Write a guide about custom scalar support in tailcall. The implementation is provided here — https://github.com/tailcallhq/tailcall/blob/main/tests/execution/test-scalars.md

**NOTE:** End the document with suggestions about creating an issue for scalars that aren't supported yet.

## Content Creation Requirements

To maintain the quality of our content, please adhere to the following guidelines:

### 1. Accuracy in Language

- **Grammar and Spelling:** Ensure your content is free from grammatical and spelling errors.

### 2. Tone and Style

- **Neutral Tone:** Maintain a neutral, non-emotional tone throughout the content.
- **Engaging Style:** Write in a free-flowing and engaging manner, keeping the reader's interest.

### 3. Content Integrity

- **Fact-Checking:** Verify all information. If unsure, use Discord to clarify.
- **Relevance:** Ensure all content is cohesive, to the point, and directly related to the title.

### 4. Originality

- **Avoid Low-Effort Content:** Content should be original and not solely generated by AI tools like ChatGPT.

**PS: Adherence to these guidelines is crucial. Content not meeting these standards may require revision or may not be accepted.**

**Comment by neo773** [comment]
/attempt #136

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;31 tailcallhq bounties <br/> + 62 bounties from 19 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">tailcallhq/tailcall#1300</div> | [Cancel attempt](https://console.algora.io/api/bounties/cltl4g81i0004jx0fch83azw8/cancel-attempt) |

**Comment by neo773** [comment]
@tusharmath 
Can we close this as completed?
