### ISSUE TITLE
Write a detailed guide for telemetry

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#140]
Telemetry is a recent feature that was integrated and documented here: 
https://tailcall.run/docs/operators/telemetry/

Write a detailed guide using the telemetry feature about how one can use it.

- Add screenshots where necessary
- Add forward/backward links to the Apollo Guide

**Comment by ghost** [comment]
/attempt #140

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cltlcvosi000cjj0f8om867ml/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by DhairyaMajmudar** [comment]
Hi @tusharmath it seems like the given link in description is broken can you pls. provide an updated one , thank you : )

**Comment by giraffekey** [comment]
/attempt #140

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/giraffekey) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @giraffekey | 1 tailcallhq bounty | <div align="center">Rust, JavaScript, <br />HTML & more</div> | <div align="center">﹟650</div> | [Cancel attempt](https://console.algora.io/api/bounties/cltlcvosi000cjj0f8om867ml/cancel-attempt) |
