### ISSUE TITLE
Update schema of Request

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#150]
The schema for JSRequest has changed https://github.com/tailcallhq/tailcall/pull/1409

Update the documentation with these changes.

**Comment by thesapan** [comment]
/attempt

<div id="algora" />

| [Algora profile](https://console.algora.io/@/thesapan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @thesapan | 2 tailcallhq bounties | <div align="center"></div> | <div align="center">tailcallhq/tailcall#1410</div> | [Cancel attempt](https://console.algora.io/api/bounties/cltpfi2tb0002l50fls03npk9/cancel-attempt) |
