### ISSUE TITLE
Write a guide about using JS to perform data transformation

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#152]
Update the `http-filters.md` with an example of modifying incoming request data.

```graphql
schema  {
  query: Query
  mutation: Mutation
}

type Mutation {
  createUser(input: InputUser): UserCreated @http(
    method: POST, 
    path: "/users", 
    query: [{key: "user", value: "{{args.input}}"}] # pass input as an argument
}

input InputUser {
  name: String
  age: Int
}
```

```js
function onRequest({request}) {
   const user = JSON.parse(decodeURIComponent(request.uri.query.user))
   request.uri.query = {}
   request.body = {
      userName: user.name,
      userAge: user.age
   }
   return {request}
}
```

Something on the above lines. 

**IMPORTANT:** Make sure you try the final configuration and that it works.

**Comment by neo773** [comment]
/attempt #152

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;34 tailcallhq bounties <br/> + 63 bounties from 20 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">tailcallhq/tailcall#1300</div> | [Cancel attempt](https://console.algora.io/api/bounties/cltpgrgat0002l10fpar4fh0i/cancel-attempt) |
