### ISSUE TITLE
Write a guide about REST api routes

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#158]
A recent new feature of exposing REST on top of GraphQL was merged https://github.com/tailcallhq/tailcall/pull/1324

Explore this feature, and write a guide for everyone else to follow. Feel free to discuss this feature on the discord channel.

**IMPORTANT**
Make your writing engaging by adding LEGIBLE screenshots.

**Comment by neo773** [comment]
/attempt #158
Could I get assigned
<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;34 tailcallhq bounties <br/> + 63 bounties from 20 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">tailcallhq/tailcall#1300, tailcallhq/tailcall#1360</div> | [Cancel attempt](https://console.algora.io/api/bounties/cltr1ykva000ejq0frfq6e9vo/cancel-attempt) |
