### ISSUE TITLE
Missing dependencies in `package.json`

### ISSUE THREAD

**Issue by adwait-godbole** [tailcallhq/tailcallhq.github.io#165]
While setting up the project locally I ran `npm i` as instructed in [README](https://github.com/tailcallhq/tailcallhq.github.io?tab=readme-ov-file#installation) and then ran `npm start` but it gave me the below set of errors:

![Screenshot (121)](https://github.com/tailcallhq/tailcallhq.github.io/assets/68469605/82eeb1ff-d6bb-489d-bfb8-eb1c5b50b286)

I think the code is using some dependencies but those haven't been listed in the `package.json` [dependencies](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/package.json#L19) and neither the [devDependencies](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/package.json#L40C4-L40C19) so they are not getting installed during `npm i`. Specifically these 3 dependencies are missing:

1) `lunr` (I am not exactly sure where its being used)

2) `react-router-dom` which is being used [here](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/src/theme/Navbar/Content/index.tsx#L4) and some more places but missing from `package.json`

3) `@docusaurus/theme-common` which is being  used [here](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/src/theme/Navbar/Content/index.tsx#L2) and some more places but missing from `package.json`

**Comment by adwait-godbole** [comment]
One note here if we now try to add `react-router-dom` in the dependencies list of `package.json` by doing 
`npm i react-router-dom` and pushing the changed `package.json` file in the repo code, [this](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/src/theme/Navbar/Content/index.tsx#L4) line of code won't work since `useHistory` has been removed by `react-router-dom` in it's latest v6 release. So we will likely have to change it to `useNavigate` as well otherwise we will have to install `react-router-dom` with the prior release that has the `useHistory`.

**Comment by adwait-godbole** [comment]
@tusharmath I can work on this issue.

**Comment by tusharmath** [comment]
Thanks @adwait-godbole ! Looking forward to your PR.

**Comment by tusharmath** [comment]
Happy to accept a PR with the fix, however, I think this might be a problem at your end. The CI works properly without any issues and it installs the packages fresh everytime.

**Comment by adwait-godbole** [comment]
Yeah while raising the issue I wondered how the CI worked so far. Can you try doing the local setup yourself once instead of the CI ? I mean for example clearly `react-router-dom` is definitely missing from [package.json](https://github.com/tailcallhq/tailcallhq.github.io/blob/c70ac159324207faaa9a75dbaf6b56f1b90f5154/package.json#L19) but being used in the code.

**Comment by adwait-godbole** [comment]
@tusharmath nvm sorry I am closing this issue. I tried on GitHub Codespaces and it worked. 

Ig whatever packages I mentioned where the internal dependencies of `Docusaurus` so it installs them by itself and there's no need to have them explicitly in the `package.json` .

For some odd reason this internal installation that Docusaurus does did not happen on my machine I'll have to look into it (maybe its the node version or npm version mismatch idk).

But yeah, sorry for this trouble.
