### ISSUE TITLE
fix the search box

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#167]
Clicking on the search box sometimes loses the focus of the cursor. Sometimes even `Cmd + K` doesn't focus the cursor on the text box. Fix it!

Go here an click on the search box.
https://tailcall.run/docs/

**Comment by 35C4n0r** [comment]
/attempt #167

<div id="algora" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;5 tailcallhq bounties <br/> + 8 bounties from 3 projects | <div align="center">Python, JavaScript, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clue4n5zd0002jk0foxzu91uf/cancel-attempt) |

**Comment by ezhil56x** [comment]
/attempt #167

<div id="algora" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 14 bounties from 9 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clue4n5zd0002jk0foxzu91uf/cancel-attempt) |

**Comment by jkcs** [comment]
/attempt #167

Why hasn't anyone been assigned?

<div id="algora" />

| [Algora profile](https://console.algora.io/@/jkcs) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @jkcs | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 12 bounties from 5 projects | <div align="center">TypeScript, Vue, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clue4n5zd0002jk0foxzu91uf/cancel-attempt) |

**Comment by tusharmath** [comment]
I think a better solution would be to use the algolia option.

**Comment by neo773** [comment]
> I think a better solution would be to use the algolia option.

Made a new PR that migrates to Algolia

**Comment by jkcs** [comment]
@tusharmath praveenn77/docusaurus-lunr-search#143 has been merged. If you don't mind continuing to use `docusaurus-lunr-search`, I can make a PR to upgrade it to v3.4.0 and add the `autoFocus` prop to achieve this functionality.

**Comment by tusharmath** [comment]
Sure.

**Comment by GM1957** [comment]
/attempt #167

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clue4n5zd0002jk0foxzu91uf/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by hrshkshri** [comment]
/attempt #167


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clue4n5zd0002jk0foxzu91uf/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
