### ISSUE TITLE
Bug: Installation docker

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#176]
Docker command to run Tailcall is incorrect

```docker run -p 8080:8080 -p 8081:8081 tailcall.docker.scarf.sh/tailcallhq/tailcall/tc-server:v0.73.0```

command doesn't work as It need additional input like 'start` subcommand config file mounting etc

**Comment by neo773** [comment]
/attempt #176

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;42 tailcallhq bounties <br/> + 65 bounties from 22 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clujmyc1u000nkx0gk3mkcvwc/cancel-attempt) |
