### ISSUE TITLE
add a contributors section on the Website

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#205]
Add a section on the website for contributors under docs. Add the following content:

1. https://github.com/tailcallhq/tailcall/blob/main/.github/contributing.md
2. https://github.com/tailcallhq/tailcall/blob/main/BOUNTY.md
3. https://github.com/tailcallhq/tailcall/blob/main/tests/README.md

**Technical Requirements**
- Create a PR to delete the content from the source repository
- Ensure the content is docusaurus optimized, with meaning routes, titles, descriptions etc.

**Comment by jemiluv8** [comment]
/attempt #205

<div id="algora" />

| [Algora profile](https://console.algora.io/@/jemiluv8) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @jemiluv8 | 26 bounties from 9 projects | <div align="center">TypeScript, HTML, <br />Rust</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cluwq47hf0002jm0flki94kwx/cancel-attempt) |

**Comment by Bhavyajain21** [comment]
/attempt #205


<div id="algora" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 4 bounties from 1 project | <div align="center">Rust, TypeScript, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cluwq47hf0002jm0flki94kwx/cancel-attempt) |

**Comment by ezhil56x** [comment]
/attempt #205

<div id="algora" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 16 bounties from 9 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cluwq47hf0002jm0flki94kwx/cancel-attempt) |
