### ISSUE TITLE
feature: Embed GraphiQL on the website

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#209]
**Technical Requirements**

- Embed GraphiQL on the `/playground` URL
- The UI should keep the top navigation bar
- Ensure the default font family is `Space Grotesk` and the monospace font family is `Space Mono`
- Create a dir called `playground` with all the playground-related components
- Ensure code is modular, understandable, and easy to refactor
- Use typescript everywhere.
- The URL should be configurable. 
	- A text box could be provided to submit the URL. 
	- The URL should also be configurable via Query Params so that tailcall CLI can be integrated.

**Comment by webbdays** [comment]
I would like to try this:
https://github.com/graphql/graphiql/tree/main/packages/graphiql#usage
will try evening.

But which backend to connect to execute Graphql queries.

**Comment by rutikthakre** [comment]
/attempt #209
Hi @tusharmath  Could you please assign to me?

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Rutik7066) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Rutik7066 | &nbsp;&nbsp;&nbsp;1 tailcallhq bounty <br/> + 4 bounties from 3 projects | <div align="center">Go, Rust, <br />TypeScript & more</div> | <div align="center">tailcallhq/tailcall#1271</div> | [Cancel attempt](https://console.algora.io/api/bounties/clv4ss165000wlb0c9y01o126/cancel-attempt) |

**Comment by webbdays** [comment]
you can try. /attempt is enough.

<div id="algora" />

| [Algora profile](https://console.algora.io/@/webbdays) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @webbdays | 1 tailcallhq bounty | <div align="center">Python, Rust, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clv4ss165000wlb0c9y01o126/cancel-attempt) |

**Comment by webbdays** [comment]
oh sorry.

**Comment by syedbarimanjan** [comment]
@tusharmath > Note
> 
> The user @Rutik7066 is already attempting to complete issue #209 and claim the bounty. We recommend checking in on @Rutik7066's progress, and potentially collaborating, before starting a new solution.

I started working on it an hour after the bounty appeared in the activity tab on Algora. I'll raise the pull request in some time.

**Comment by syedbarimanjan** [comment]
@tusharmath should I put a link to the playground in the navbar?

**Comment by syedbarimanjan** [comment]
@tusharmath GraphiQL doesn't have a light mode. Should I create one, or is dark mode alright?

**Comment by webbdays** [comment]
Unless it is a urgent requirement, please give a chance to the person who attempted it first until their attempt failed/expired.
@Rutik7066 attempted it first and may be he has a local changes.
