### ISSUE TITLE
[feature]:Add dark mode

### ISSUE THREAD

**Issue by syedbarimanjan** [tailcallhq/tailcallhq.github.io#211]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

There should be a dark mode. I am willing to implement it if your designer provides me the colors or if you dont have a designer we can decide the colors together.

### Why should this be worked on?

As a developer I am all of the time on my pc and if the screen is bright my eyes hurt.

### Repository

tailcallhq.github.io

**Comment by tusharmath** [comment]
We don't have this yet, however I agree with you. The white can get quite jarring. Until we figure out the final version of the color codes, feel free to create a dark theme, I'd be more than happy to merge it.

**Comment by syedbarimanjan** [comment]
> We don't have this yet, however I agree with you. The white can get quite jarring. Until we figure out the final version of the color codes, feel free to create a dark theme, I'd be more than happy to merge it.

I'll do my best to make a dark theme that fits well with our branding.
