### ISSUE TITLE
[bug]: The current favicon is not properly visible

### ISSUE THREAD

**Issue by syedbarimanjan** [tailcallhq/tailcallhq.github.io#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The favicon should be changed to have a light background so it is properly visible.

### Steps to reproduce

see

### Repository

tailcallhq.github.io

**Comment by tusharmath** [comment]
@syedbarimanjan Thanks for the report! This is what I see at the moment:

<img width="332" alt="Screenshot 2024-04-22 at 10 55 59 AM" src="https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/95775a1a-ceb6-4efd-a8cb-8964f0819360">

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan Thanks for the report! This is what I see at the moment:
> 
> <img alt="Screenshot 2024-04-22 at 10 55 59 AM" width="332" src="https://private-user-images.githubusercontent.com/194482/324337697-95775a1a-ceb6-4efd-a8cb-8964f0819360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU5NjgsIm5iZiI6MTcxMzc2NTY2OCwicGF0aCI6Ii8xOTQ0ODIvMzI0MzM3Njk3LTk1Nzc1YTFhLWNlYjYtNGVmZC1hOGNiLTg5NjRmMDgxOTM2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwNjAxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjFmNGRmNzM0ZDJiY2E0ZmY1ZTJlNjI4NGYxYTU4N2M1NzMxYmVkN2EzMzIzYWQ5ZDVkZTk4Y2E2MTQ2MmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dUg4XCG8tTKWJ4IgdLWG3J2y9tFJnEhCTNMzQu5JTyQ">

if you turn the browser to a dark theme it wont be properly visible.
![Screenshot from 2024-04-22 11-02-55](https://github.com/tailcallhq/tailcallhq.github.io/assets/112156147/9c897583-0121-45a8-ae0a-06cf8bb3075e)

**Comment by tusharmath** [comment]
Happy to accept a PR, if you can conditionally load this favicon for dark themed browsers.

![tailcall-icon](https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/b2511c88-8ed1-4daf-8e12-1bad8213bb7f)

**Comment by syedbarimanjan** [comment]
> Happy to accept a PR, if you can conditionally load this favicon for dark themed browsers.
> 
> ![tailcall-icon](https://private-user-images.githubusercontent.com/194482/324347920-b2511c88-8ed1-4daf-8e12-1bad8213bb7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Njc2NjYsIm5iZiI6MTcxMzc2NzM2NiwicGF0aCI6Ii8xOTQ0ODIvMzI0MzQ3OTIwLWIyNTExYzg4LThlZDEtNGRhZi04ZTEyLTFiYWQ4MjEzYmI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwNjI5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmNmMGNiMjM4YWU1ODgzYWRiMTkyOWM2NTYwM2YxNzYyNWFjMzY4MDc3NzAwMzRmNTEwZTU2MjE2ZTRkZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AFwDKnzMMuKKxy8LSZ6-SvszurwkYrvUpRwI_RnhSSY)

I am on it
