### ISSUE TITLE
add footer on docs

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#230]
There is a footer on the home page, but it's not visible on the docs page. 

**Technical Requirements**
- Ensure it's added to all the pages on the website
- Ensure it doesn't need to be specified everytime on every page.

**Comment by jordan-ae** [comment]
/attempt #230

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvqrlpbj0002l109i69le578/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by laststylebender14** [comment]
/attempt #230

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvqrlpbj0002l109i69le578/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ezhil56x** [comment]
/attempt #230


<div id="algora" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;4 tailcallhq bounties <br/> + 20 bounties from 9 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvqrlpbj0002l109i69le578/cancel-attempt) |
