### ISSUE TITLE
Add a `/developers` route

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#242]
Instead of using `https://tailcall.run/docs/contributors/` we wish to have have another route `https://tailcall.run/developers` where all the developers of Tailcall can understand and contribute to the codebase.

**Technical Requirements**
- Create a new route `/developers`
- Update the home page top nav with `Home | Docs | Blog | Developers`
- Have `/developers` have it's own side-nav

**Comment by mehulmathur16** [comment]
/attempt #242

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mehulmathur16) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mehulmathur16 | &nbsp;&nbsp;&nbsp;7 tailcallhq bounties <br/> + 8 bounties from 4 projects | <div align="center">TypeScript, Rust, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvxgzpq40008l409jzh566rl/cancel-attempt) |

**Comment by infysumanta** [comment]
/attempt #242

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvxgzpq40008l409jzh566rl/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
