### ISSUE TITLE
Merge all directive pages into one and move it to guide

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#255]
Each directive has its own page, which seems unnecessary. We should merge them together into one page and move that into guides.

**Comment by neo773** [comment]
/attempt #255

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;46 tailcallhq bounties <br/> + 70 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwxe5qp20004jt09epy5w839/cancel-attempt) |

**Comment by ezhil56x** [comment]
/attempt #255

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;7 tailcallhq bounties <br/> + 24 bounties from 10 projects | <div align="center">JavaScript, TypeScript, <br />Rust & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwxe5qp20004jt09epy5w839/cancel-attempt) |

**Comment by tusharmath** [comment]
By merge I mean, combine them into one page :)
