### ISSUE TITLE
merge n+1 pages

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#256]
Merge all the N + 1 pages into one and move it under guide.

**Comment by 35C4n0r** [comment]
/attempt #256

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;5 tailcallhq bounties <br/> + 13 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwxe6vs7000cml09wnhukwex/cancel-attempt) |

**Comment by 35C4n0r** [comment]
@tusharmath In this do we want to merge all N+1 pages in a single page and move it to Usage Guides?

**Comment by tusharmath** [comment]
By merge I mean, combine them into one page :)

**Comment by Bhavyajain21** [comment]
Merged in One!
