### ISSUE TITLE
Improve doc meta information

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#268]
For each content piece in `/doc` we need to improve the quality of meta information.

- `title`
- `description`
- `slug`

Feel free to use the following link to suggest titles and descriptions for each page by simply pasting the content (without the meta information) in the input.

https://chatgpt.com/g/g-xEV4Wm2A7-content-descriptor

**Comment by 35C4n0r** [comment]
/attempt #268

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;6 tailcallhq bounties <br/> + 13 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwxnol1v0002ld09shf7536d/cancel-attempt) |

**Comment by dnyaneshwar-rede** [comment]
/attempt #268

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clwxnol1v0002ld09shf7536d/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by CeoJeanette** [comment]
"claim"
 ```/attempt #268```
*The Fix (What you will do):*
Once claimed, you need to update the *Docusaurus* configuration and page metadata. I have drafted the three core changes below:
1. *Global Metadata (```docusaurus.config.js```):*
Ensure the ```themeConfig``` includes a robust default description and Open Graph tags.
```themeConfig: {
  metadata: [
    {name: 'keywords', content: 'GraphQL, API, performance, orchestration, tailcall'},
    {name: 'description', content: 'The high-performance GraphQL platform for modern API orchestration.'},
  ],
}```

2. *Page-Specific Meta (Front Matter):*
Every ```.md``` file in the ```/docs``` folder needs a unique ```description```. I can help you generate these using the *Master Architect* tone.
  - _Example:_ ```description: "Learn how to orchestrate complex API architectures with Tailcall's high-performance GraphQL engine."```

3. *Canonical URLs:*
Add a ```url``` field to ```docusaurus.config.js``` to prevent duplicate indexing—a "Master Move" for SEO.
