### ISSUE TITLE
[docs]: Addition of contributing guide

### ISSUE THREAD

**Issue by Haimantika** [tailcallhq/tailcallhq.github.io#275]
### What do you want to add to the docs? (please state reasons if any)

Currently the org wide Contributing Guidelines page throws a 404 error. We should add it, as the repo also involves bounty, having a contributing guide will add certain rules to how contribution happens and give everyone a fair chance.

From a quick scan I found that there was a certain issue that was being worked on by two contributors - https://github.com/tailcallhq/tailcallhq.github.io/pull/246 and https://github.com/tailcallhq/tailcallhq.github.io/pull/247 

From the time stamp it is clear that the later took up the issue after it was already being worked on by the former (even the code looks similar with very slight changes).

Adding a contributing guide mentioning all of these would be helpful and prevent such happenings in the future. 

### Repository

tailcall

**Comment by syedbarimanjan** [comment]
@Haimantika https://tailcall.run/developers/bounty/ here is the bounty guide which can change based on the circumstances.

**Comment by Haimantika** [comment]
> @Haimantika https://tailcall.run/developers/bounty/ here is the bounty guide which can change based on the circumstances.

1. I was mentioning about contributing guides, since the page throws a 404 error.
2. The guide you shared says:
“ No Copycats: Be original; be yourself. Avoid merely copying someone else's hard work.
Consider Before You Contribute: If there’s already a PR in progress, perhaps take a moment to review it before submitting your own.”

And there is clearly a breach of these two rules. :)

**Comment by tusharmath** [comment]
Thanks @Haimantika!

>Currently the org wide Contributing Guidelines page throws a 404 error. We should add it, as the repo also involves bounty, having a contributing guide will add certain rules to how contribution happens and give everyone a fair chance.

I updated the readme here https://github.com/tailcallhq/tailcall/blob/main/README.md

I think we need to specify steps for contributors to identify plagiarism. Let me write something up.

**Comment by tusharmath** [comment]
Added this section, hope it helps our future contributors — https://tailcall.run/developers/bounty/#identifying-plagiarism

**Comment by Haimantika** [comment]
> Added this section, hope it helps our future contributors — https://tailcall.run/developers/bounty/#identifying-plagiarism

This is helpful! Thanks :)
