### ISSUE TITLE
[bug]: Fix 404 pages

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Here are some of the pages where we are getting 404s. Fix them by adding appropriate redirects.

1. `/about`
2. `/about/`
3. `/docs/guides/n+1/`
4. `/docs/intro/architecture`
5. `/docs/intro/architecture/`
6. `/docs/intro/cli/`
7. `/docs/intro/operators/`
8. `/docs/intro/server`
9. `/docs/intro/server/`
10. `/docs/operators/add-field/`
11. `/docs/operators/graphql/`
12. `/docs/operators/http/`
13. `/docs/operators/server/`
14. `/docs/operators/telemetry/`
15. `/docs/operators/upstream/`
16. `/enterprise/`
17. `/docs/n+1/introduction/`

Where should it redirect to is up to the developer to decide. Generally all docs pages still exist but are named something else.

### Steps to reproduce

The information is private and only available to admins.

### Repository

tailcallhq.github.io

**Comment by DhairyaMajmudar** [comment]
Hi @tusharmath can you pls. assign this to me

/attempt

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx4figxv0002la09p7qg5w4t/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Bhavyajain21** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 9 bounties from 2 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx4figxv0002la09p7qg5w4t/cancel-attempt) |

**Comment by 35C4n0r** [comment]
My bad, accidentally linked the wrong issue.
