### ISSUE TITLE
[feature]: Improve website sitemap

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#277]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

The sitemap doesn't contain information about all the docs pages. We need to generate a sitemap that contains all our docs pages.

Currently this sitemap is available here https://tailcall.run/sitemap.xml

### Why should this be worked on?

Sitemaps are critical for SEO.

### Repository

tailcallhq.github.io

**Comment by 35C4n0r** [comment]
/attempt #277

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;6 tailcallhq bounties <br/> + 13 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx4fla0y000hla09vx4dujft/cancel-attempt) |

**Comment by DhairyaMajmudar** [comment]
/attempt 

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx4fla0y000hla09vx4dujft/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
