### ISSUE TITLE
Publish blogs automatically from github to hashnode

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#301]
Currently, we publish blogs directly on hashnode - https://blog.tailcall.run/
Going forward we want to write blogs on this website and publish on hashcode automatically.

**Technical Requirements**
- All the meta information and artwork should be reused from the blogs here.
- It should happen automatically on every commit after a successful build.

**Comment by bnchi** [comment]
/attempt #301

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cly5tgshf000ul3090tyu3ma7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by b4s36t4** [comment]
@tusharmath I think hashnode does provide github as a blog provider which automatically pulls each `md` file and push to hashnode.

Doesn't that work for you? you want to render mdx to hashnode or expecting any other in the sense write blog directly on website and publish to hashnode or so?!

**Comment by bnchi** [comment]
> @tusharmath I think hashnode does provide github as a blog provider which automatically pulls each `md` file and push to hashnode.
> 
> Doesn't that work for you? you want to render mdx to hashnode or expecting any other in the sense write blog directly on website and publish to hashnode or so?!

Correct, and to extend on this, the feature seem to be for PRO users.

https://support.hashnode.com/en/articles/8119381-how-to-publish-articles-from-github

**Comment by tusharmath** [comment]
>@tusharmath I think hashnode does provide github as a blog provider which automatically pulls each md file and push to hashnode.
Yes I know but then the format is very specific to Hashnode, we want to also publish to dev.to, medium, substack etc. with the canonical tags pointing to our main website.


In reality we want to move out of Hashnode, but we have quite a few subscribers who follow us and would not like them to migrate to some other platform. 

> Doesn't that work for you? you want to render mdx to hashnode or expecting any other in the sense write blog directly on website and publish to hashnode or so?!
Blogs won't be in `mdx` format it would always be in `md` format.

**Comment by tusharmath** [comment]
They also have some GraphQL APIs - https://apidocs.hashnode.com
We could use those.
