### ISSUE TITLE
Update the guide for GraphQL with react

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#309]
We need to enhance our existing guide on integrating various GraphQL clients in React by adding new sections and details to make it more comprehensive and useful for developers. Here are the specific updates needed:

**Bundle Size Comparison:**

Update the existing comparison table to include the bundle size for each client. 

**Caching Capabilities:**

Expand the comparison table for caching mechanisms supported by each GraphQL client.

**Error Handling Section:**

Provide a detailed discussion on error handling for each client. Include code examples showing how to gracefully catch and handle different types of GraphQL errors (e.g., network errors, query errors).
Add subsections that guide developers on displaying error messages in the UI in a user-friendly manner.

**Common Issues and Resolutions section:**

Create a new section addressing common issues developers might encounter when using each GraphQL client with React. Provide troubleshooting steps and solutions for these problems.
This update will ensure our guide remains a valuable resource by providing practical, in-depth information tailored to real-world development challenges.

This is the base PR. Create a PR against this
https://github.com/tailcallhq/tailcallhq.github.io/pull/308

**Comment by asr2003** [comment]
I would like to take solve this issue and mark my first contribution in tailcall @tusharmath 
/attempt #309

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/asr2003) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @asr2003 | 1 bounty from 1 project | <div align="center">JavaScript, Go, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cly8fhtbe000al509tmhlmpcc/cancel-attempt) |

**Comment by onyedikachi-david** [comment]
/attempt #309

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | 2 bounties from 1 project | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cly8fhtbe000al509tmhlmpcc/cancel-attempt) |

**Comment by mukeshblackhat** [comment]
/attempt #309



<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cly8fhtbe000al509tmhlmpcc/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by amitksingh1490** [comment]
Fixed in #313
