### ISSUE TITLE
Auto Publish Blogs to Dev.to

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#357]
Like Hashnode, we wish to publish our blogs to https://dev.to/ automatically whenever we publish on our main blog on this website.

**Technical Requirements**
- New blogs should be automatically published.
- Old blogs should be updated.
- Canonical tags should be added to the blogs published on dev.to 
- All meta information should be copied over at dev.to

**Update 1**
- Ensure publishing happens in parallel to hashnode.

**Comment by ssddOnTop** [comment]
/attempt #357

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ssddOnTop) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ssddOnTop | 57 tailcallhq bounties | <div align="center">Rust, Java, <br />C & more</div> | <div align="center">﹟2349, ﹟2389</div> | [Cancel attempt](https://console.algora.io/api/bounties/clypgyhlt0004l909l7yf23e4/cancel-attempt) |

**Comment by hunxjunedo** [comment]
/attempt #357

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hunxjunedo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hunxjunedo | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 4 bounties from 2 projects | <div align="center">JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clypgyhlt0004l909l7yf23e4/cancel-attempt) |
