### ISSUE TITLE
Create a unified GraphQL endpoint to post blogs to multiple publishers

### ISSUE THREAD

**Issue by neo773** [tailcallhq/tailcallhq.github.io#360]
Create a unified GraphQL endpoint that allows us to publish posts to any publisher. 

**Technical Requirements**
- Use Tailcall to generate a unified GraphQL endpoint
- Support Hashnode and Dev.to
- Update publisher logic on the CI to publish using this new endpoint

**Comment by Bhavyajain21** [comment]
/attempt #360


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyv6nlev0013mr097y8nsfrc/cancel-attempt) |

**Comment by swaingotnochill** [comment]
/attempt #360


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clyv6nlev0013mr097y8nsfrc/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by harshtech123** [comment]
/ attempt #360

**Comment by onyedikachi-david** [comment]
/attempt #360

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 2 bounties from 1 project | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyv6nlev0013mr097y8nsfrc/cancel-attempt) |
