### ISSUE TITLE
Update the tailcall configuration on Getting Started section with the complete JsonPlaceholder configuration

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#374]
Add a section with a full tailcall configuration for JsonPlaceholder, start from the below configuration.

```graphql
schema @server @upstream(baseURL: "https://jsonplaceholder.typicode.com") {
  query: Query
}

type Address {
  city: String
  geo: Geo
  street: String
  suite: String
  zipcode: String
}

type Company {
  bs: String
  catchPhrase: String
  name: String
}

type Geo {
  lat: String
  lng: String
}

type Photo {
  albumId: Int
  id: Int
  thumbnailUrl: String
  title: String
  url: String
}

type Post {
  body: String
  id: Int
  title: String
  userId: Int
}

type Comment {
  body: String
  email: String
  id: Int
  name: String
  postId: Int
}

type Query {
  comment(id: Int!): Comment @http(path: "/comments/{{.args.id}}")
  comments: [Comment] @http(path: "/comments")
  photo(id: Int!): Photo @http(path: "/photos/{{.args.id}}")
  photos: [Photo] @http(path: "/photos")
  post(id: Int!): Post @http(path: "/posts/{{.args.id}}")
  posts: [Post] @http(path: "/posts")
  todo(id: Int!): Todo @http(path: "/todos/{{.args.id}}")
  todos: [Todo] @http(path: "/todos")
  user(id: Int!): User @http(path: "/users/{{.args.id}}")
  users: [User] @http(path: "/users")
}

type Todo {
  completed: Boolean
  id: Int
  title: String
  userId: Int
}

type User {
  address: Address
  company: Company
  email: String
  id: Int
  name: String
  phone: String
  username: String
  website: String
}
```

**Technical Requirements**
- Use `@call` to add relationships between types.
- Add YML and JSON versions also.
- Ensure configurations are validated via the Tailcall CLI

**Comment by neo773** [comment]
/attempt #374

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;52 tailcallhq bounties <br/> + 74 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyvdcixn0008me09hdbjucon/cancel-attempt) |

**Comment by Bhavyajain21** [comment]
/attempt #374


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center">﹟360, ﹟373</div> | [Cancel attempt](https://console.algora.io/api/bounties/clyvdcixn0008me09hdbjucon/cancel-attempt) |

**Comment by harshtech123** [comment]
hey @tusharmath tailcall cli as per documentation is not working , for npm or yarn as well 
https://tailcall.run/docs/#installing-the-tailcall-cli is this correct ?

**Comment by tusharmath** [comment]
What's not working?

**Comment by harshtech123** [comment]
this Ensure configurations are validated via the Tailcall CLI
i am runninf tailcall - validate but it is saying tailcall is not a command and i also try to install tailcall by running commands as per above documentation , can you please tell me how to validate ?

**Comment by harshtech123** [comment]
/attempt #378 

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clyvdcixn0008me09hdbjucon/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by onyedikachi-david** [comment]
/attempt #374

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 2 bounties from 1 project | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyvdcixn0008me09hdbjucon/cancel-attempt) |
