### ISSUE TITLE
Write a Post Outline for Exploring GraphiQL: The In-Browser IDE for GraphQL

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#375]

**Comment by shegz101** [comment]
@amitksingh1490 I am working on this.

**Comment by shegz101** [comment]
> @shegz101: You've been awarded a **$20** bounty by **tailcallhq**! 👉 [Complete your Algora onboarding](https://console.algora.io/solve) to collect the bounty.

Still yet to be rewarded. What could be the issue?
