### ISSUE TITLE
UI: Update the home-page with the below design

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#394]
Look at the [figma](https://www.figma.com/design/mMLCy6XZinopm6QrEqOovP/Tailcall-Website-Redesign---Shared?node-id=2913-221752&t=7kQIe07EkBDxiJ2n-0) design and add the following sections on the home page

> Our customers love us

> Tailcall gives you a ...

**Technical Requirements**
- Ensure the UI matches exactly withe design
- Ensure the UI is responsive (Design for mobile exists)
- Reuse existing UI components and CSS as much as possible
- Ensure your PR contains minimal changes 
- Write documentation about your changes wherever possible

**Comment by Bhavyajain21** [comment]
/attempt #394

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;3 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">Rust, TypeScript, <br />JavaScript & more</div> | <div align="center">﹟2521</div> | [Cancel attempt](https://console.algora.io/api/bounties/clz1bfsij0004lc09nsf42zxw/cancel-attempt) |

**Comment by mehulmathur001** [comment]
/attempt #394

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mehulmathur001) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mehulmathur001 | 3 tailcallhq bounties | <div align="center">C++</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz1bfsij0004lc09nsf42zxw/cancel-attempt) |

**Comment by Bhavyajain21** [comment]
@tusharmath Could you please provide the dev mode access for figma?

**Comment by Bhavyajain21** [comment]
Can I be assigned? @tusharmath
