### ISSUE TITLE
Issue: Syntax Highlighting Not Working for Vue Code in Code Blocks

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#409]
**Description:**
Syntax highlighting for Vue code is not functioning correctly in code blocks. When using the Vue language tag (`vue`) in a code block, the syntax highlighting does not render as expected. Below is an example:

```markdown
```vue
<script setup lang="ts">
import { useQuery } from "@urql/vue";
import { ref, computed } from "vue";

const postsQuery = `
  query GetPosts($limit: Int!, $offset: Int!) {
    posts(limit: $limit, offset: $offset) {
      id
      title
    }
  }
`;

const limit = ref(10);
const offset = ref(0);

const { data, fetching, error } = useQuery({
  query: postsQuery,
  variables: computed(() => ({
    limit: limit.value,
    offset: offset.value,
  })),
});

const loadMore = () => {
  offset.value += limit.value;
};
</script>
```

**Expected Behavior:**
The code should display with proper syntax highlighting for Vue components, including script, template, and style sections.

**Actual Behavior:**
The code does not display with the expected syntax highlighting, making it harder to read and understand.

**Screenshot**
<img width="699" alt="image" src="https://github.com/user-attachments/assets/525a8939-99ef-4174-ab63-831e9789c491">

**Comment by beelchester** [comment]
/attempt #409

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/beelchester) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @beelchester | 7 tailcallhq bounties | <div align="center">Rust, TypeScript, <br />CSS & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzcs6otk000sl109kd17kbr1/cancel-attempt) |
