### ISSUE TITLE
Fix CI in #412

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#413]
Create a PR WRT to https://github.com/tailcallhq/tailcallhq.github.io/pull/412

- Proof read identify gaps
- Make the build pass
- Optimize uploaded images

**Comment by mukeshblackhat** [comment]
/attempt #413



<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clzfajulc0002l709fk27pnty/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by mukeshblackhat** [comment]
@tusharmath   i have created a pr against your branch with which you have created the pr , is it ok or should i also create one new direct pr form mine to develop

**Comment by mukeshblackhat** [comment]
@tusharmath the redirection is not woking properly in the case , i want to know how to conferm the re direction is woking properly
