### ISSUE TITLE
Drop `grid-dark.png`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#418]
Drop `grid-dark.png` and use CSS to produce the same effect. It is used in the footer images.

**Comment by 35C4n0r** [comment]
/attempt #418

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;7 tailcallhq bounties <br/> + 17 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzfocjop0002l709tfog6410/cancel-attempt) |

**Comment by Bhavyajain21** [comment]
/attempt #418

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;4 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzfocjop0002l709tfog6410/cancel-attempt) |

**Comment by hunxjunedo** [comment]
/attempt #418

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hunxjunedo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hunxjunedo | &nbsp;&nbsp;&nbsp;5 tailcallhq bounties <br/> + 4 bounties from 2 projects | <div align="center">JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzfocjop0002l709tfog6410/cancel-attempt) |
