### ISSUE TITLE
Document request batching

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#42]
The PR was implemented here — https://github.com/tailcallhq/tailcall/pull/520

We need to add documentation for the new setting `enableBatchRequests`

Take the documentation tips from https://www.apollographql.com/blog/apollo-client/performance/batching-client-graphql-queries/

**NOTE:**
Make sure documentation is meaningful and people can actually understand what we are enabling them with.

**Comment by neo773** [comment]
Can I ge assigned

**Comment by mrkirthi-24** [comment]
I would like to work on this issue
