### ISSUE TITLE
Add the features section to home page

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#420]
Refer to the designs here — https://www.figma.com/design/mMLCy6XZinopm6QrEqOovP/Tailcall-Website-Redesign---Shared?node-id=2913-221752&t=ImOZMgbhPu8a9kMe-0

After the performance section there is a section called "More reasons to chose tailcall." That's currently missing from the website. 

**Technical Requirement**
- Most components already exist so avoid creating new stuff
- Ensure performance of the home page isn't compromised.

**Comment by Bhavyajain21** [comment]
/attempt #420

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;4 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">TypeScript, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzfp0hcl0002l909l3bcl5x8/cancel-attempt) |

**Comment by Oms-343** [comment]
/attempt #420

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clzfp0hcl0002l909l3bcl5x8/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
