### ISSUE TITLE
Use anchor tags in the benefits section

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#431]
The home page benefits section uses divs instead of anchor tags, change that to links so that it's crawlable by the SEO.

**Comment by 35C4n0r** [comment]
/attempt  431

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;8 tailcallhq bounties <br/> + 18 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzpf4tzt0004l009jpd4i6xs/cancel-attempt) |

**Comment by ezhil56x** [comment]
/attempt 431

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;7 tailcallhq bounties <br/> + 35 bounties from 11 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzpf4tzt0004l009jpd4i6xs/cancel-attempt) |

**Comment by akhilender-bongirwar** [comment]
/attempt 431

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clzpf4tzt0004l009jpd4i6xs/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by 35C4n0r** [comment]
@tusharmath I have a hunch that the merged PR will introduce a bug in Smaller Screens (Mobile).

**Comment by 35C4n0r** [comment]
![image](https://github.com/user-attachments/assets/9a55feb4-fba8-4e68-9964-539cb10d00f6)

**Comment by neo773** [comment]
This fixes it https://github.com/tailcallhq/tailcallhq.github.io/pull/435

**Comment by 35C4n0r** [comment]
Nope that introduces a new bug
Your's
![image](https://github.com/user-attachments/assets/d54f4983-f5de-4d67-8986-6f5cc7faa7f6)

Original
![image](https://github.com/user-attachments/assets/fa1e1348-ee12-40aa-9089-00f4251f23a9)

**Comment by neo773** [comment]
> Nope that introduces a new bug Your's ![image](https://private-user-images.githubusercontent.com/70096901/356868952-d54f4983-f5de-4d67-8986-6f5cc7faa7f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzQ4MjUsIm5iZiI6MTcyMzM3NDUyNSwicGF0aCI6Ii83MDA5NjkwMS8zNTY4Njg5NTItZDU0ZjQ5ODMtZjVkZS00ZDY3LTg5ODYtNmY1Y2M3ZmFhN2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDExMDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZWEwYWQ2OGQ2NjAwYjM3NTg0M2YwNzRiYWU2NjQzYTg3ODMwMDViMTNkMmY1NTIwZWVjY2Q1MWJhOGI4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aMhdGMWIGsIlcf8VsvLVHykQY-UUG_gmjTjo0CK0nEw)
> 
> Original ![image](https://private-user-images.githubusercontent.com/70096901/356869228-fa1e1348-ee12-40aa-9089-00f4251f23a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzQ4MjUsIm5iZiI6MTcyMzM3NDUyNSwicGF0aCI6Ii83MDA5NjkwMS8zNTY4NjkyMjgtZmExZTEzNDgtZWUxMi00MGFhLTkwODktMDBmNDI1MWYyM2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDExMDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmIwMTJhZjU0ZjM0YTJlODk5ZTYyZGYzZjQ1MjA1NzNlMDFlZTU3NTBiNzI3NGViMTkwZWE5NTkwMTA0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wQZoVElsOJ-IcsU3yf87dRUNB9fqZpq1HF_2q7L1yfI)

Ah, didn't realise since I don't have the original reference anymore

**Comment by neo773** [comment]
Pushed an update, Thanks.
<img width="409" alt="SCR-20240811-osdn" src="https://github.com/user-attachments/assets/2e37b0eb-be50-4828-83cc-c93fe8106d35">
