### ISSUE TITLE
fix layout of the benefits section.

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#445]
Issue: The title horizontal alignment doesn't match the content below it.

**Comparison**
<img width="2226" alt="Screenshot 2024-08-15 at 5 47 05 PM" src="https://github.com/user-attachments/assets/e2f0882a-4c3d-47b5-b3d3-320eaca39afc">

**Technical Requirements**
- Ensure the layouts work in all screen sizes.

**Comment by 35C4n0r** [comment]
/attempt #445

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;9 tailcallhq bounties <br/> + 18 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzv8ydma0002la094w3t938d/cancel-attempt) |

**Comment by neo773** [comment]
/attempt #445

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;55 tailcallhq bounties <br/> + 74 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzv8ydma0002la094w3t938d/cancel-attempt) |

**Comment by DhairyaMajmudar** [comment]
/attempt #445

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/DhairyaMajmudar) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @DhairyaMajmudar | 1 bounty from 1 project | <div align="center">JavaScript, HTML, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzv8ydma0002la094w3t938d/cancel-attempt) |
