### ISSUE TITLE
fix "deploy anywhere" section

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#447]
The carousal is getting clipped in wide screens. Ideally it should touch both ends of the screen.

<img width="2560" alt="Screenshot 2024-08-15 at 5 59 01 PM" src="https://github.com/user-attachments/assets/776ef82f-d9ce-4882-82f1-3a523a2f9cd8">

**Comment by 35C4n0r** [comment]
/attempt #447

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/35C4n0r) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @35C4n0r | &nbsp;&nbsp;&nbsp;9 tailcallhq bounties <br/> + 18 bounties from 4 projects | <div align="center">Python, HTML, <br />JavaScript & more</div> | <div align="center">﹟445</div> | [Cancel attempt](https://console.algora.io/api/bounties/clzv9dfa50002l909rhjfufrl/cancel-attempt) |

**Comment by akhilender-bongirwar** [comment]
/attempt #447 

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clzv9dfa50002l909rhjfufrl/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
