### ISSUE TITLE
Document `@server(responseHeaders)` 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#46]

**Comment by rajdip-b** [comment]
@tusharmath can you provide some more details about this?

**Comment by Min2who** [comment]
can you assign me this @tusharmath

**Comment by tusharmath** [comment]
@Min2who Let's have @rajdip-b contribute to this one, since he messaged first.

**Comment by rajdip-b** [comment]
sure thing!

**Comment by rajdip-b** [comment]
@tusharmath can you review the PR please?
