### ISSUE TITLE
Move the announcement banner to the top of the nav

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#466]
Make it look like this —

<img width="1279" alt="Screenshot 2024-08-26 at 9 35 17 PM" src="https://github.com/user-attachments/assets/2700f24d-185e-4108-b0e5-8b46e336e041">

**Technical Requirements**
- Ensure there is no duplication
- Ensure the UI is responsive and works on all screen sizes

**Comment by neo773** [comment]
/attempt #466

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;56 tailcallhq bounties <br/> + 74 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0b6yelm0004lc03b69j9wv7/cancel-attempt) |
