### ISSUE TITLE
Bug Report: API Triggered on Disabled Button Click

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#469]
#### **Current Behavior**
When the email field is filled, the button remains in a disabled state. However, clicking the button still triggers the API request, even though the button is not enabled.

#### **Expected Behavior**
The API should only be triggered when the button is enabled, which should only happen after an answer is selected for the "What stage of GraphQL are you in?" question.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/cbfabd54-716f-4dce-a081-8ec5c0bcaef7">

**Comment by beelchester** [comment]
/attempt #469

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/beelchester) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @beelchester | 10 tailcallhq bounties | <div align="center">Rust, TypeScript, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0gchqhm0004ju03x3apy986/cancel-attempt) |
