### ISSUE TITLE
Redesign the blog page

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#472]
Attaching a high-resolution image of the redesigned blog page:

**Technical Requirements**
- UI should exactly match the design without exceptions.
- The navigation isn't in the design but should remain at the top.
- You are free to skip design elements that require a specialized backed and doesn't exist.
- Should work on mobile and desktop without any issues.
- Should not affect the performance of the page.
- Follow DRY principle and maximize reusability thru components.

**Good to Have**
- Improving existing code in a significant way will earn you a tip.
- Make the life of the reviewer easy by adding comments around your codebase.

![Detailed blogs-V1 (1)](https://github.com/user-attachments/assets/7c21a19c-07b2-43f9-98c7-a8335a5abbac)

**Comment by neo773** [comment]
/attempt #472

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;58 tailcallhq bounties <br/> + 74 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0gpjizs001gmh03ox4imhfs/cancel-attempt) |

**Comment by csgaikwad** [comment]
@tusharmath Some questions:

- For the "Related Blogs" section at the bottom, do we prefer multiple suggestions? If so, should we implement a horizontal scrolling list for better visibility? Alternatively, should we only display a limited number of blogs?

**Comment by csgaikwad** [comment]
/attempt #472


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0gpjizs001gmh03ox4imhfs/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
