### ISSUE TITLE
Redesign Landing Page for the Blog

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#475]
Update the blog home page design as per the new design:

<img width="4274" alt="Blog Landing Page-V1" src="https://github.com/user-attachments/assets/5c70bbd9-aa82-41cc-8866-06e655200a79">

**Technical Requirements**
- Search bar isn't required at the moment.
- For "featured posts" use front matter to extract that information.
- Load more should load all the blogs.
- Tabs represent categories and should also be loaded from front matter.
- UI should be responsive.

**Comment by Aditya-rajput200** [comment]
We need to degin the landing page as per the ui provided?

**Comment by Aditya-rajput200** [comment]
/attempt #475

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by tribhuwan-kumar** [comment]
/attempt #475

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Nitin6404** [comment]
/attempt #475 

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by hunxjunedo** [comment]
/attempt #475

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hunxjunedo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hunxjunedo | &nbsp;&nbsp;&nbsp;6 tailcallhq bounties <br/> + 4 bounties from 2 projects | <div align="center">JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt) |

**Comment by tusharmath** [comment]
Anyone close to completion on this? I am happy to take it up internally otherwise.

**Comment by Nitin6404** [comment]
@tusharmath I'm working on it.

**Comment by mohdaquib171** [comment]
/attempt #475

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Srujithchaithanya1** [comment]
/attempt #475

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by iamhvsharma** [comment]
/attempt #475


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0klj1kw0004k103daxqqt6m/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
