### ISSUE TITLE
[bug]: search box isn't available on desktop mode in docs section.

### ISSUE THREAD

**Issue by laststylebender14** [tailcallhq/tailcallhq.github.io#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Search box isn't present on docs section of website on desktop mode but available on mobile mode.

## Desktop mode:
![image](https://github.com/user-attachments/assets/f7ab0dc3-66bc-4aad-933c-5d768a9ffbee)

## Mobile mode:
<img width="1440" alt="Screenshot 2024-09-04 at 11 07 33 PM" src="https://github.com/user-attachments/assets/27dc1864-49ab-4db0-ad60-456bee83d030">

### Steps to reproduce

1. Open website in desktop mode and navigate to docs section, you won't find search box to search something.
2. Open website in mobile mode and navigate to docs section, you'll find search box to search something.

### Repository

tailcallhq.github.io

**Comment by neo773** [comment]
/attempt #479

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;60 tailcallhq bounties <br/> + 75 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0o5a17k0002kx03pcicboog/cancel-attempt) |
