### ISSUE TITLE
Embed Tailcall Introduction Video on the Home Page

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#481]
Embed this video link - https://www.youtube.com/watch?v=-hgzB5JhWJQ

**Technical Requirements**
- Ensure the UI matches the design below.
- Ensure the UI is responsive and the video is visible on all screensizes.
- Ensure there is not performance degradation produced because of this page.

<img width="1728" alt="v2 1 - Homepage" src="https://github.com/user-attachments/assets/b4914a39-48d1-4a43-abce-ac887a28be49">

![Mobile - v2 1](https://github.com/user-attachments/assets/d4b8e234-caaa-4686-b1c0-04e2c98edf68)

**Comment by Bhavyajain21** [comment]
/attempt #481

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Bhavyajain21) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Bhavyajain21 | &nbsp;&nbsp;&nbsp;4 tailcallhq bounties <br/> + 11 bounties from 2 projects | <div align="center">Rust, TypeScript, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0rli1ru0002l40339xj0w76/cancel-attempt) |

**Comment by Nitin6404** [comment]
/attempt #481

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0rli1ru0002l40339xj0w76/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by hunxjunedo** [comment]
/attempt #481

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hunxjunedo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hunxjunedo | &nbsp;&nbsp;&nbsp;6 tailcallhq bounties <br/> + 4 bounties from 2 projects | <div align="center">JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0rli1ru0002l40339xj0w76/cancel-attempt) |

**Comment by tusharmath** [comment]
IMPORTANT: We got an update from the design team. Have a look below:

**Key Changes**
- A light grey grid has been added in the BG
- A border radius of 24px has been added
- A vimeo video has been added (I'll share that shortly)


![v2 1 - Homepage (1)](https://github.com/user-attachments/assets/2952e63b-686b-488d-8744-b46b72bc992b)

**Comment by tusharmath** [comment]
Here is the video to embed — 

```html
<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/1011521201?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Tailcall Introduction"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
```
