### ISSUE TITLE
Migrate to Algolia for search

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#496]
**Technical Requirements**

- Lunr index should be disabled
- No affect on page performance
- UI Should look exactly as before

**Comment by ArDnath** [comment]
/attempt #496 Replace Lunr search functionality with Algolia.
Update the search frontend logic to query the Algolia API instead of Lunr. Can I be assigned this Issue seems like a good weekend project


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm1bgocup0002l503jmd70wqp/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by bnchi** [comment]
Did you apply for the DocSearch program ? @tusharmath 

https://docusaurus.io/docs/3.0.1/search#using-algolia-docsearch

> DocSearch crawls your website once a week (the schedule is configurable from the web interface) and aggregates all the content in an Algolia index.

> The service is free for any open-source project.

**Comment by tusharmath** [comment]
Received this email from Algolia:

---



### CSS

Copy this snippet at the end of the HTML `<head>` tag:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3"/>
```

### JavaScript

Copy this snippet at the end of the HTML `<body>` tag:

```html
<script src="https://cdn.jsdelivr.net/npm/@docsearch/js@3"></script>

<script type="text/javascript">
  docsearch({
    appId: "X27WDVHRQ3",
    apiKey: "35bc100f239853cd8a7195b23ed7393b",
    indexName: "tailcall",
    container: '### REPLACE ME WITH A CONTAINER (e.g. div) ###',
    debug: false
  });
</script>
```

**Comment by ArDnath** [comment]
Nice ,this makes it easier than working on it
