### ISSUE TITLE
Embed YouTube Video and remove Call to Action in Dream11 GraphQL Case Study Blog

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#502]
We need to embed the following YouTube video: [https://www.youtube.com/watch?v=Esb7oQ0PuXw](https://www.youtube.com/watch?v=Esb7oQ0PuXw) into the **Dream11 GraphQL Case Study** blog (https://tailcall.run/blog/dream11-graphql-case-study/).

Requirements:
- Embed the video and remove the call to action buttons.
- Ensure that the video fits naturally into the existing flow of the blog without feeling abrupt or out of place.
- Make sure the blog remains responsive to various screen sizes
  
The goal is to integrate the video smoothly while maintaining the readability and structure of the blog.

**Comment by saisandeepramavath** [comment]
/attempt #502

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm1emevcg0002ku033hjznday/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
