### ISSUE TITLE
404 Error on the website

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#506]
Going to the home page issues a 404 error for loading a CSS file that doesn't exist.

<img width="855" alt="Screenshot 2024-09-25 at 7 54 48 AM" src="https://github.com/user-attachments/assets/ffe9755c-55f4-449b-8b30-ef674d302cdf">

**Comment by EveEdwin** [comment]
/attempt #506 

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm1h8ud2r0004mh037uer7jd9/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ArDnath** [comment]
/attempt #506 this error is concerned with clearbitscripts configurational Setting @tusharmath you mannually will have to change tags.js configuration in clearbit ,if possible disable clearbit forms or get form attributes hidden from the tags.js imported here
![Screenshot from 2024-09-25 10-15-35](https://github.com/user-attachments/assets/5b16bcef-f2db-4d94-9cca-769414489288)
