### ISSUE TITLE
The text "Search" and the icon are both visible.

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#509]
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/23c54810-262c-40fe-821e-fe1661f8e9e2">

For IPad Air resolutions

**Comment by syedbarimanjan** [comment]
/attempt #509

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | &nbsp;&nbsp;&nbsp;1 tailcallhq bounty <br/> + 7 bounties from 3 projects | <div align="center">TypeScript, HTML, <br />Ruby & more</div> | <div align="center">﹟510</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm1hevugq0004le037wnhg310/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
@amitksingh1490 can not reproduce this.

![Screenshot from 2024-09-25 10-22-46](https://github.com/user-attachments/assets/8c76e4da-0496-4589-9713-95c4e16fc14f)

**Comment by amitksingh1490** [comment]
Might have got fix due to some previous PR closing for Now @syedbarimanjan
