### ISSUE TITLE
Split `configuration.md`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#510]
Split the current file — https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/ 
into smaller pages for each directive. 

**Technical Requirements**

- Keep the current page as an over of all the operators that are available.
- Update the links to point to the individual pages
- Add individual pages under the `features` section
- Some operators already have pages so:
	1. Update the link to point to the existing page.
	2. Update the existing page with information that was missing.
- The title of the page should be the problem that operator solves.

**Comment by syedbarimanjan** [comment]
/attempt #510

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | &nbsp;&nbsp;&nbsp;1 tailcallhq bounty <br/> + 7 bounties from 3 projects | <div align="center">TypeScript, HTML, <br />Ruby & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm1heqiuf0002mb03ytvhwbfp/cancel-attempt) |

**Comment by tusharmath** [comment]
We will split this into smaller issues.
