### ISSUE TITLE
Triggers for layout change for search comp is not in sync with the triggers in sidenav

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#511]
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/ca7ec881-2f87-4017-921d-2ebb716952d7">

Triggers for layout change for search comp is not in sync with the triggers in sidenav

For instance in this screenshot the side nav is collapsed to hamburger menu but the search modal is still following the desktop based layout

**Comment by akhilender-bongirwar** [comment]
![image](https://github.com/user-attachments/assets/bbaa1c8f-bc66-47ff-94da-46449a681236)


@amitksingh1490, unable to reproduce the bug.

**Comment by amitksingh1490** [comment]
Happening for me 
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/0e5323c1-1513-4245-8ce5-6330ab0c8e14">

**Comment by Mubashirshariq** [comment]
@amitksingh1490 in local env it is working fine ,but i tried the tailcall/run/docs there i can reproduce the issue

<img width="951" alt="Screenshot 2024-09-25 at 1 52 06 PM" src="https://github.com/user-attachments/assets/65311e20-bb40-411a-bb85-9eec18a42287">
