### ISSUE TITLE
Use cypress to write initial set of tests

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#512]
Integrate https://docs.cypress.io to test the website in production mode. Start with some basic tests such as —

1. There are no errors or warnings on the console. 

**Technical Requirements**
- Integrate it with npm test
- Test should run on production build using 
- `npm run build`

**Comment by beelchester** [comment]
/attempt tailcallhq/tailcallhq.github.io#512


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/beelchester) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @beelchester | 12 tailcallhq bounties | <div align="center">Rust, TypeScript, <br />Shell & more</div> | <div align="center">﹟2820</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm1hekxtp000qmi03bpupqf6w/cancel-attempt) |

**Comment by hunxjunedo** [comment]
@tusharmath I implemented this, and asked for a review before raising a PR: https://github.com/hunxjunedo/tailcallhq.github.io/tree/cyprus-tests

**Comment by tusharmath** [comment]
Hey @hunxjunedo next time just raise a PR so that it's easier to manage. Thanks!
