### ISSUE TITLE
doc: update documentation for `Context`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#88]
Add information about using 

- Environment variables
- Variables

Briefly touch upon how mustache templates can be used to access context in directives.

**Comment by chaos-stotch** [comment]
Can I be assigned to this?

**Comment by tusharmath** [comment]
@chaos-stotch Go ahead please!

**Comment by xonx4l** [comment]
can I get assigned?? I have idea ready.

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by wesleymatosdev** [comment]
this should be closed I guess @tusharmath
