### ISSUE TITLE
Write a guide about doing sequence and parallel calls

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#89]
Write a guide about how one can do sequence and parallel calls in Tailcall. Tailcall automatically identifies the fastest way to get data. If something can be done in parallel, it will happen automatically without the user explicitly marking something as parallel. Write a guide about how this happens.

## Content Creation Requirements
To maintain the quality of our content, please adhere to the following guidelines:

### 1. Accuracy in Language
- **Grammar and Spelling:** Ensure your content is free from grammatical and spelling errors.

### 2. Tone and Style
- **Neutral Tone:** Maintain a neutral, non-emotional tone throughout the content.
- **Engaging Style:** Write in a free-flowing and engaging manner, keeping the reader's interest.

### 3. Content Integrity
- **Fact-Checking:** Verify all information. If unsure, use Discord to clarify.
- **Relevance:** Ensure all content is cohesive, to the point, and directly related to the title.

### 4. Originality
- **Avoid Low-Effort Content:** Content should be original and not solely generated by AI tools like ChatGPT.

**PS: Adherence to these guidelines is crucial. Content not meeting these standards may require revision or may not be accepted.**

**Comment by pi600** [comment]
can i work on it?

**Comment by tusharmath** [comment]
Yes @pi600

**Comment by tareknaser** [comment]
If @pi600 is not working on this issue, could i get assigned?

**Comment by tareknaser** [comment]
/attempt https://github.com/tailcallhq/tailcallhq.github.io/issues/89
