### ISSUE TITLE
doc:  N+1 guide needs to explain how to enable batching on upstream

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#95]
If I take the code from the N+1 guide and run check on it.
It says groupBy can be used only if batching is enabled.
This guide doesn't explain how to enable batching

**Comment by ibishal** [comment]
so we need to explain how to enable batchin in the n+1 guide right?

cc @amitksingh1490 @tusharmath

**Comment by amitksingh1490** [comment]
> so we need to explain how to enable batchin in the n+1 guide right?
> 
> cc @amitksingh1490 @tusharmath 

yes

**Comment by 35C4n0r** [comment]
@tusharmath I would like to solve this.

**Comment by tusharmath** [comment]
@35C4n0r go ahead.

**Comment by 35C4n0r** [comment]
/attempt #95

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clt6jvv1f0002jy0gd74s8zc8/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by tusharmath** [comment]
@amitksingh1490 This is a bug more than a feature. Sorry @Bhavyajain21 I don't we need this anymore.
